import { useState } from "react";
import { api } from "../api";
import { Badge, Bars, Card, errorText } from "./ui";

const PRESETS = [
  "Why was this customer classified as high risk?",
  "Which transactions should be investigated first and why?",
  "What suspicious relationships are visible in this customer's network?",
  "Summarize this customer's AML history.",
  "What evidence should an investigator review?",
];

function refHref(r: { type: string; id: string }): string | null {
  switch (r.type) {
    case "customer":
      return `#/customers/${r.id}`;
    case "account":
    case "device":
      return `#/graph?kind=${r.type}&id=${r.id}`;
    case "transaction":
      return `#/search?q=${r.id}`;
    case "investigation":
      return `#/investigations/${r.id}`;
    default:
      return r.id.startsWith("MAL-") ? `#/alerts/${r.id}` : null;
  }
}

function Refs({ refs }: { refs?: { type: string; id: string }[] }) {
  const uniq = [...new Map((refs ?? []).map((r) => [`${r.type}:${r.id}`, r])).values()].slice(0, 6);
  if (!uniq.length) return null;
  return (
    <span className="muted small">
      {" "}
      [{uniq.map((r, i) => {
        const h = refHref(r);
        return (
          <span key={`${r.type}:${r.id}`}>
            {i > 0 && ", "}
            {h ? <a href={h}>{r.id}</a> : r.id}
          </span>
        );
      })}]
    </span>
  );
}

// Grounded question answering about one customer. Every statement comes from FIRA data and cites entity ids; the AI paragraph
// (if any) is labelled as interpretation and is never presented as evidence.
export default function Copilot({ customerId, investigationId }: { customerId: string; investigationId?: string }) {
  const [q, setQ] = useState(PRESETS[0]);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const [r, setR] = useState<any>(null);

  const ask = async (question: string) => {
    setBusy(true);
    setErr(null);
    try {
      setR(await api.post("/api/copilot/ask", { customer_id: customerId, question, investigation_id: investigationId }));
    } catch (e) {
      setErr(errorText(e));
    } finally {
      setBusy(false);
    }
  };

  return (
    <Card title="AI Investigation Copilot">
      <p className="muted small">
        Answers are built from FIRA's own records (database, risk engine, graph). Facts and derived signals cite the entities they come from; the
        interpretation paragraph is AI-generated text, validated against those entities, and is not evidence. Synthetic data only.
      </p>
      <div className="row wrap">
        {PRESETS.map((p) => (
          <button key={p} disabled={busy} onClick={() => { setQ(p); ask(p); }}>{p.replace(/\?$/, "").replace("this customer's ", "")}</button>
        ))}
      </div>
      <form className="row" style={{ marginTop: 8 }} onSubmit={(e) => { e.preventDefault(); ask(q); }}>
        <input value={q} maxLength={500} onChange={(e) => setQ(e.target.value)} style={{ flex: 1 }} aria-label="question" />
        <button className="primary" disabled={busy || q.trim().length < 3}>{busy ? "Retrieving evidence…" : "Ask"}</button>
      </form>
      {err && <div className="error">{err}</div>}
      {r && (
        <div style={{ marginTop: 10 }}>
          {r.status === "insufficient_evidence" && <div className="notice">Insufficient evidence: {r.limitations[0]}</div>}
          {r.risk && (
            <p>
              <b>Risk score {r.risk.risk_score}</b> <Badge value={r.risk.risk_level} kind={r.risk.risk_level.toLowerCase()} />{" "}
              <span className="muted small">(deterministic, configuration {r.risk.config_version})</span>
            </p>
          )}
          <p>{r.summary}</p>
          {r.risk_factors.length > 0 && (
            <>
              <h4><Badge value="DERIVED SIGNAL" /> Risk factors and contribution</h4>
              <Bars data={r.risk_factors.map((f: any) => ({ label: f.factor, value: f.contribution, note: f.capped ? "(capped)" : "" }))} max={40} />
            </>
          )}
          <h4><Badge value="OBSERVED FACT" /> from the database</h4>
          <ul className="plain">{r.observed_facts.map((f: any, i: number) => <li key={i}>{f.statement}<Refs refs={f.refs} /></li>)}</ul>
          {r.derived_signals.length > 0 && (
            <>
              <h4><Badge value="DERIVED SIGNAL" /> computed by FIRA analytics</h4>
              <ul className="plain">{r.derived_signals.slice(0, 12).map((s: any, i: number) => <li key={i}>{s.statement} <span className="muted small">({s.source})</span><Refs refs={s.refs} /></li>)}</ul>
            </>
          )}
          <h4><Badge value="AI INTERPRETATION" kind="medium" /> not evidence</h4>
          <p>{r.interpretation.text}</p>
          <p className="muted small">Generated by: {r.interpretation.generated_by}. Statements were checked against {r.grounding.allowed_entity_ids} entity ids in the evidence package.</p>
          {r.recommendations.length > 0 && (
            <>
              <h4><Badge value="RECOMMENDATION" kind="high" /> system recommendation, not a legal conclusion</h4>
              <ul className="plain">{r.recommendations.map((x: any, i: number) => <li key={i}>{x.statement}</li>)}</ul>
            </>
          )}
          <details className="small"><summary>Evidence referenced ({r.evidence.length})</summary>
            <ul className="plain">{r.evidence.slice(0, 40).map((e: any) => <li key={`${e.type}${e.id}`}><Refs refs={[e]} /> {e.why}</li>)}</ul>
          </details>
          <h4>Limitations</h4>
          <ul className="plain">{r.limitations.map((x: string, i: number) => <li key={i} className="muted">{x}</li>)}</ul>
        </div>
      )}
    </Card>
  );
}
